# Generated by Django 4.2.4 on 2023-08-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='departure_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='class_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='depart',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
