# Generated by Django 4.2.4 on 2023-08-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_remove_booking_departure_at_booking_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights_avaliable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=64, null=True)),
                ('To', models.CharField(max_length=10, null=True)),
                ('departure_at', models.DateField()),
                ('arrival_at', models.DateField()),
                ('seat_avaliability', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
