# Generated by Django 4.2.4 on 2023-08-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_flight_details_delete_flights_avaliable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight_details',
            new_name='Flight_detail',
        ),
    ]
