# Generated by Django 4.2.4 on 2023-08-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_rename_flight_details_flight_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_detail',
            old_name='created_at',
            new_name='Create_at',
        ),
        migrations.AlterField(
            model_name='flight_detail',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flight_detail',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
    ]
