# Generated by Django 4.2.4 on 2023-08-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_rename_created_at_flight_detail_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_detail',
            old_name='To',
            new_name='Destination',
        ),
        migrations.RenameField(
            model_name='flight_detail',
            old_name='arrival_date',
            new_name='Destination_date',
        ),
        migrations.RenameField(
            model_name='flight_detail',
            old_name='departure_time',
            new_name='Destination_time',
        ),
        migrations.RenameField(
            model_name='flight_detail',
            old_name='From',
            new_name='Origin',
        ),
        migrations.RemoveField(
            model_name='flight_detail',
            name='Create_at',
        ),
        migrations.RemoveField(
            model_name='flight_detail',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='flight_detail',
            name='seat_avaliability',
        ),
        migrations.AddField(
            model_name='flight_detail',
            name='Date_now',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='flight_detail',
            name='Origin_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='flight_detail',
            name='Origin_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight_detail',
            name='Seat_avaliability',
            field=models.IntegerField(null=True),
        ),
    ]
