# Generated by Django 4.2.4 on 2023-08-07 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_rename_to_flight_detail_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origin', models.CharField(max_length=64, null=True)),
                ('Destination', models.CharField(max_length=10, null=True)),
                ('Preferred_Seating', models.CharField(max_length=64, null=True)),
                ('Departure_date', models.DateField(null=True)),
                ('Return_date', models.DateField(null=True)),
                ('Date_now', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='flight_detail',
            name='Date_now',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
