# Generated by Django 4.2.4 on 2023-08-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_user_booking_alter_flight_detail_date_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_booking',
            name='Email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_booking',
            name='Full_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user_booking',
            name='Mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
