# Generated by Django 4.2.4 on 2023-08-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_user_booking_email_user_booking_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_booking',
            name='Adult',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_booking',
            name='Child',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_booking',
            name='Infant',
            field=models.IntegerField(null=True),
        ),
    ]
