# Generated by Django 4.2.4 on 2023-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0011_user_booking_adult_user_booking_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_booking',
            name='Child',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='Infant',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
