# Generated by Django 4.2.4 on 2023-08-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_alter_user_booking_child_alter_user_booking_infant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_booking',
            name='Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.profile'),
        ),
    ]
