# Generated by Django 4.2.4 on 2023-08-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0013_user_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_booking',
            name='Id',
        ),
        migrations.AddField(
            model_name='user_booking',
            name='user_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
