# Generated by Django 4.2.4 on 2023-08-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0014_remove_user_booking_id_user_booking_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_booking',
            old_name='user_name',
            new_name='User_Name',
        ),
    ]
